name: Deploy (Fly.io)

on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types: [completed]

concurrency:
  group: fly-deploy-chowsr
  cancel-in-progress: true

jobs:
  deploy-chowsr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chowsr
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --config fly.toml --remote-only
